name: .NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1' # Pas aan naar je .NET versie
    - name: Build met dotnet
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test
